import type { Metadata } from "next";
import "@styles/globals.css";
import TopBar from "@components/Topbar";
import Sonner from "@components/Sonner";
import Footer from "@components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="text-sm md:text-base">
          <Sonner />
          <TopBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
