import type { Metadata } from "next";
import "@styles/globals.css";
import TopBar from "@components/Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <TopBar />
          {children}
        </main>
      </body>
    </html>
  );
}
